language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install --upgrade pip pytest

script: pytest

after_success:
  - pip install codecov
  - codecov

# deploy:
#   provider: pypi
#   user: lpozo
#   password:
#     secure:
#   distributions: sdist bdist_wheel
#   on:
#     repo: lubepy/lubepy
#     tags: true
